### ISSUE TITLE
query_api::account

### ISSUE THREAD

**Issue by vivalaakam** [haqq-network/haqq-clients#2]
Method `query_api::account` returns only the account type without any additional information. There should be an additional field with raw field data or an enum.

Current response
```
Ok(CosmosPeriodAuthPeriodV1beta1PeriodQueryAccountResponse { account: Some(GooglePeriodProtobufPeriodAny { at_type: Some("/ethermint.types.v1.EthAccount") }) })
```

**Comment by onsails** [comment]
Rest API client was experimental and is now removed due to buggy openapi-generator-cli
